"""Add is_deleted to employees

Revision ID: b80bf7e3bc92
Revises: b624e8bc6ef7
Create Date: 2026-07-16 12:44:55.704979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80bf7e3bc92'
down_revision: Union[str, Sequence[str], None] = 'b624e8bc6ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_deleted')
    # ### end Alembic commands ###
